# Netlify configuration for the React app
# Building the example app which includes the crossword component demo
# and Firebase database verification

[build]
  base = "example"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers can be added here if needed
# [[headers]]
#   for = "/*"
#   [headers.values]
#   X-Frame-Options = "SAMEORIGIN"
#   X-Content-Type-Options = "nosniff"
#   Referrer-Policy = "strict-origin-when-cross-origin"
